"""Added stop_loss_price

Revision ID: 1836ab60b31d
Revises: 38b54d9b631e
Create Date: 2024-12-22 12:11:43.915406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1836ab60b31d'
down_revision: Union[str, None] = '38b54d9b631e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('stop_loss_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'stop_loss_price')
    # ### end Alembic commands ###