"""Add entry_price and exit_price to trades

Revision ID: 38b54d9b631e
Revises: 88f59b6b2842
Create Date: 2024-12-20 14:17:56.735774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38b54d9b631e'
down_revision: Union[str, None] = '88f59b6b2842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('entry_price', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('exit_price', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('timestamp', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_column('trades', 'timestamp')
    op.drop_column('trades', 'exit_price')
    op.drop_column('trades', 'entry_price')
    # ### end Alembic commands ###