"""Added close_timestamp for Trade and profit_loss

Revision ID: 3d6b2217bae1
Revises: e3bf270b97af
Create Date: 2024-12-22 12:18:29.487852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d6b2217bae1'
down_revision: Union[str, None] = 'e3bf270b97af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('profit_loss', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('close_timestamp', sa.DateTime(), nullable=True))
    op.drop_column('trades', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('trades', 'close_timestamp')
    op.drop_column('trades', 'profit_loss')
    # ### end Alembic commands ###