"""Added take_profit field to Trade

Revision ID: e3bf270b97af
Revises: 1836ab60b31d
Create Date: 2024-12-22 12:13:28.073179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3bf270b97af'
down_revision: Union[str, None] = '1836ab60b31d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('take_profit_price', sa.Float(), nullable=True))
    op.drop_column('trades', 'profit_loss')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('profit_loss', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('trades', 'take_profit_price')
    # ### end Alembic commands ###